### ISSUE TITLE
More detailed usage examples

### ISSUE THREAD

**Issue by Ruff9** [foraker/rspec_profiling#14]
I just discover your gem, and thank you, I needed exactly that. 

I'm currently trying for the first time, and I'm a little frustrated by your Readme: under the usage section, you explain how to choose a version control system or a data collector, but not how to use your gem. 

I guess I'll find out eventually, but if the explanations were more detailed, it would have been easier and faster.

**Comment by artfuldodger** [comment]
Thanks for raising the concern! The documentation could definitely need some help.

I added a couple more examples of using the results. Is this helpful?

https://github.com/foraker/rspec_profiling/commit/6185bec5b09d6ec543332e702aef05f2efc49bc4

**Comment by artfuldodger** [comment]
Closing but would always appreciate contributions of additional documentation to clarify things.

**Comment by Ruff9** [comment]
Thanks, I'll submit a pull request if I feel like it deserves more.
