### ISSUE TITLE
Track the branch name in addition to the commit

### ISSUE THREAD

**Issue by rymai** [foraker/rspec_profiling#18]
At GitLab we're interested in profiling our test suite and tracking our progress in reducing its duration over time.

To do that, we want to be able to track the suite duration for a given branch (`master` in that particular case).

This could be as simple as:

1. Adding a column in the collectors: https://github.com/foraker/rspec_profiling/blob/master/lib/rspec_profiling/collectors/psql.rb#L27-L41
1. Add a method in the various VCS implementation (e.g. using `git rev-parse --abbrev-ref HEAD` for Git): https://github.com/foraker/rspec_profiling/blob/master/lib/rspec_profiling/vcs/git.rb
1. Store the branch name in `RspecProfiling::Run#example_finished`: https://github.com/foraker/rspec_profiling/blob/master/lib/rspec_profiling/run.rb#L29-L42

**Comment by artfuldodger** [comment]
Thanks for this. Published as version 0.0.5.

**Comment by rymai** [comment]
@artfuldodger Awesome, thank you!
