### ISSUE TITLE
Using commit as a column name causes undue care when creating queries

### ISSUE THREAD

**Issue by seigel** [foraker/rspec_profiling#20]
As "commit" is a keyword used with transactions, I believe that is causing some users (like me) to get frustrated for not reason.  I believe changing it to "commit_hash" or back to "commit_sha" would solve the problem and not ruin things.

Cheers
James

**Comment by seanfisk** [comment]
@seigel Agreed. Also complicating matters is the fact that Active Record generates invalid SQL for escaping that name under certain circumstances (not an issue in this library, but it does make it more difficult to query). I would support changing the name to make it easier to query.

**Comment by ideasasylum** [comment]
I made a PR with this change from `commit` to `commit_hash`: https://github.com/foraker/rspec_profiling/pull/21

**Comment by kbrock** [comment]
nice PR. think this issue can be closed
